[package]
name = "e2d2"
version = "0.2.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>"]
build = "build.rs"

[lib]
doctest = false

[dependencies]
libc = ">= 0.2.4"
time = ">=0.1.0"
getopts = "*"
byteorder = "*"
clippy = { version = "*", optional = true }
fnv = "*"
twox-hash = "1.1.1"
regex = "0.2.10"
lazy_static = "*"
net2 = "*"
# NIX restricts us to just unix for now, we can fix this if someone cares at a later point.
nix = "*"
# Figure out if we want this permanently or just for now.
rust-sctp = { git="https://github.com/netsys/rust-sctp", optional = true}
toml = "0.4.5"
# Hack for SHM
uuid= { version = "*", features=["v4"] }
error-chain = "0.11.0"
# etcdv3-rs={ git="https://github.com/apanda/etcdv3-rs" }
tokio-core=">=0.1.8"
futures=">=0.1.14"

[features]
default = []
performance = []
dev = ["clippy"]
packet_offset = []
sctp = ["rust-sctp"]

[build-dependencies]
# Use Bindgen to generate DPDK structures.
bindgen = "0.33.0"
