#!/bin/bash
#
# Copyright (c) 2018 University of Utah
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Export DPDK bindings to the current shell.
export LD_LIBRARY_PATH=$(pwd)/net/target/native

cd db

# Check for a TOML file with client related configuration.
if [[ ! -f client.toml ]]; then
    echo "Missing client.toml file (in db directory)."
    exit -1
fi

# Get the "use_invoke" field from the client configuration. The output file
# will be markes with the value of this field, allowing to distinguish between
# experiments run with an invoke based YCSB, and experiments run with a native
# operation based YCSB.
invoke=$(cat client.toml | grep "use_invoke" | awk '{ print $NF }')

# The number of tenants requests are being generated for. Each data point in the
# output file is marked with this number.
tenants=$(cat client.toml | grep "num_tenants" | awk '{ print $NF }')

# The skew with which tenants are chosen by the client. Each data point in the
# output file is marked with this number.
tenant_skew=$(cat client.toml | grep "tenant_skew" | awk '{ print $NF }')

# The different server cores that YCSB will generate load for.
cores=(1 2 4 8)

# The different request rates that the YCSB client will be configured and run
# with.
rates=(1000000)

# Header for the output file. Required inorder to plot the results.
echo "Offered 50 99 Thrpt Tenants TSkew Cores" > ../ycsb_invoke_"$invoke".out

set_rates() {
    if [ "$invoke" == "true" ]
    then
        if [ $1 -eq 1 ]
        then
            rates=(200000 225000 250000 275000 300000)
        elif [ $1 -eq 2 ]
        then
            rates=(300000 325000 350000 375000 400000)
        elif [ $1 -eq 4 ]
        then
            rates=(500000 525000 550000 575000 600000)
        elif [ $1 -eq 8 ]
        then
            rates=(950000 975000 1000000 1025000 1050000)
        fi
    else
        if [ $1 -eq 1 ]
        then
            rates=(275000 300000 325000 350000 375000)
        elif [ $1 -eq 2 ]
        then
            rates=(400000 425000 450000 475000 500000)
        elif [ $1 -eq 4 ]
        then
            rates=(675000 700000 725000 750000 775000)
        elif [ $1 -eq 8 ]
        then
            rates=(1150000 1175000 1250000 1275000 1300000)
        fi
    fi
}

# Run YCSB stressing a different number of server cores.
for core in ${cores[@]}
do
    # Configure the client TOML file with the number of cores to stress.
    sed -i "s/server_udp_ports = [1-9][0-9]*/server_udp_ports = $core/g" client.toml

    # Set the list of request rates that YCSB should generate.
    set_rates $core

    # Run YCSB for each of the above request rates.
    for rate in ${rates[@]}
    do
        echo "rate=$rate, invoke=$invoke, tenants=$tenants, tenant_skew=$tenant_skew, cores=$core"

        # Configure the client TOML file with the request rate.
        sed -i "s/req_rate = [1-9][0-9]*/req_rate = $rate/g" client.toml

        # Run YCSB, and write out the median, 99th, and throughput.
        RUST_LOG=debug ./target/release/ycsb 2>&1 | grep "Median(ns)" | \
                awk "{ print $rate, \$3, \$5, \$7, $tenants, $tenant_skew, $core }" \
                >> ../ycsb_invoke_"$invoke".out
    done
done

exit 0
