#!/bin/bash

export LD_LIBRARY_PATH=$(pwd)/net/target/native

cd db

if [[ ! -f server.toml ]]; then
    echo "Missing server.toml file (in db directory)."
    exit -1
fi

RUST_LOG=debug ./target/release/server
