#!/bin/bash
#
# Copyright (c) 2018 University of Utah
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Export DPDK bindings to the current shell.
export LD_LIBRARY_PATH=$(pwd)/net/target/native

cd splinter

# Check for a TOML file with client related configuration.
if [[ ! -f client.toml ]]; then
    echo "Missing client.toml file (in db directory)."
    exit -1
fi

# Remove pre-existing samples.temp file.
rm -rf ../samples.temp

# The number of tenants requests are being generated for. Each data point in the
# output file is marked with this number.
tenants=$(cat client.toml | grep "num_tenants" | awk '{ print $NF }')

# The skew with which tenants are chosen by the client. Each data point in the
# output file is marked with this number.
tenant_skew=$(cat client.toml | grep "tenant_skew" | awk '{ print $NF }')

# The number of server cores being stressed by TAO. Each data point in the
# output file is marked with this number.
cores=$(cat client.toml | grep "server_udp_ports" | awk '{ print $NF }')

# Run TAO, and write out the median, 99th, and throughput.
RUST_LOG=debug ./target/release/tao >> ../samples.temp

Amean=$(cat ../samples.temp | grep "AMean" | \
    awk 'BEGIN { sum = 0 } { sum += $2 } END { print sum/8 }')

Amed=$(cat ../samples.temp | grep "AMean" | \
    awk 'BEGIN { sum = 0 } { sum += $4 } END { print sum/8 }')

Atail=$(cat ../samples.temp | grep "AMean" | \
    awk 'BEGIN { sum = 0 } { sum += $6 } END { print sum/8 }')

Omean=$(cat ../samples.temp | grep "AMean" | \
    awk 'BEGIN { sum = 0 } { sum += $8 } END { print sum/8 }')

Omed=$(cat ../samples.temp | grep "AMean" | \
    awk 'BEGIN { sum = 0 } { sum += $10 } END { print sum/8 }')

Otail=$(cat ../samples.temp | grep "AMean" | \
    awk 'BEGIN { sum = 0 } { sum += $12 } END { print sum/8 }')

thrpt=$(cat ../samples.temp | grep "AMean" | \
    awk 'BEGIN { sum = 0 } { sum += $14 } END { print sum }')

echo "AMean(ns): $Amean, AMedian(ns): $Amed, ATail(ns): $Atail, OMean(ns): $Omean, OMedian(ns): $Omed, OTail(ns): $Otail, Throughput: $thrpt"

# Cleanup temp file.
rm -rf ../samples.temp
