#!/bin/bash
#
# Copyright (c) 2018 University of Utah
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Export DPDK bindings to the current shell.
export LD_LIBRARY_PATH=$(pwd)/net/target/native

cd db

# Check for a TOML file with client related configuration.
if [[ ! -f client.toml ]]; then
    echo "Missing client.toml file (in db directory)."
    exit -1
fi

# The request rate that the Bad client will be configured and run with.
rate=750000

# Configure the client TOML file with the request rate.
sed -i "s/req_rate = [1-9][0-9]*/req_rate = $rate/g" client.toml

# If a command line argument was provided, use it as a request rate for YCSB.
if [ $# -eq 1 ]
then
    # Configure the client TOML file with the bad rate.
    sed -i "s/bad_ptm = [0-9][0-9]*/bad_ptm = $1/g" client.toml

    # Remove any preexisting temp files.
    rm -f ../samples.temp

    # Run YCSB.
    RUST_LOG=debug ./target/release/bad >> ../samples.temp

    # Calculate the total throughput.
    thrpt=$(cat ../samples.temp | grep "BAD Throughput" | \
            awk 'BEGIN { sum = 0 } { sum += $3 } END { print sum }')

    # Print out final numbers.
    m=$(cat ../samples.temp | grep ">>>" | awk '{ print $2 }')
    t=$(cat ../samples.temp | grep ">>>" | awk '{ print $3 }')
    echo ""
    echo "Median(ns): $m, Tail(ns): $t, Throughput(op/s): $thrpt"
    rm -f ../samples.temp

    exit 0
fi
